### ISSUE TITLE
News to notes - Part 3 - Metadata, notes display revamping and multilingual

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/MIPs#128]
## Rationale

We have two different editors for rich content: news and notes.
This can create bad UX for users. Differences are:
- editor options richer in the notes editor
- translation only for notes
- Mobile view for news editor only
- other items: emoji in title, mentions, news with same title, etc.

In addition to this, the news provide options to add featured image and summary while it is not possible for notes

Users give us feedback about these differencies and this makes uneasy the onboarding.
Our proposition is to unify the experience of both editing. The only difference remains into organizing contents (notes) and into publishing contents (news)

### Common Editor improvement
_Unification of editor for News based on Note editor_
- the News editor will be based on the note editor

_Metadata_
- Common metadata drawer between notes and news to add complementary information to the content
- Metadata drawer available from the editor
- Metadatas: 
  - Featured image
  - Summary
    - I can add emoji and tags
- All the metadata should be changed according to the translation choice

_Translation_
- Add the translation option for the news

_Mobile editor harmonization_
- No metadata button in mobile
- Add a X to close the editor and going back to the page where we open the editor
- Switch to display the edition options in 2 parts
- Only layout options: 
    - bold
    - italic
    - bullet list
    - number list
    - quote

_Other small improvement_

- be able to mention a user in a note or news

- Be able to add emoji on the title
- Be able to create a news or note with the same title, no matter the location on the treeview or the space
- Save button harmonization
- Save button UX improvement : no more close of the editor
  - Notes: success snackbar with the possibility to view the notes
  - News: 
     - creation: 
       - Before first publication: open the publication drawer and after publication a success snackbar with the possibility to view the articles. 
       - After the first publication: we display a save button and no more publication drawer. 
     - edition: save button and success snackbar 

- Remove Cancel button for news case
- Change the header editor image to replace with a font awesome icon. 
- Same modification will be applied on SNV editor. We will use notes editor for SNV 

Design for Note and SNV editor
**Creation**
![image](https://github.com/Meeds-io/MIPs/assets/105866381/73f7d8fe-d227-4900-aff7-7d185fa443fa)

**Edition**
![image](https://github.com/Meeds-io/MIPs/assets/105866381/995a582c-30d5-40c8-b3ac-dd7e853b1757)

Design for News editor
**Creation**
_Before first publication_
![image](https://github.com/Meeds-io/MIPs/assets/105866381/10595f4e-5e4b-41e6-909c-516aaec07d34)

_After first publication_
![image](https://github.com/Meeds-io/MIPs/assets/105866381/df0e7acc-46f9-4f32-80a2-3283109ffe85)

**Edition**
![image](https://github.com/Meeds-io/MIPs/assets/105866381/a705401d-a71f-4f79-af32-0d3439500610)

### Notes
- Expand drawer for the treeview
- UI revamping of the 3 dots menu

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/6c64f642-f9fa-4c02-bbc9-9af5b9f53c98)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/7339248f-4b46-4c22-9230-8b239813a4cd)

-  Note display revamping to being able to display the Metadata
**Note - Title and body**
![image](https://github.com/Meeds-io/MIPs/assets/105866381/218cff20-a232-4555-8910-f52718a54d18)

**Note - Title, body + summary**
![image](https://github.com/Meeds-io/MIPs/assets/105866381/0c7a839d-eb42-48cb-bc52-017140dac6ff)

**Note - Title, body + featured image**
![image](https://github.com/Meeds-io/MIPs/assets/105866381/dfb0fe87-7821-4223-8031-a7492f833671)

**Note - Title, body + featured image + summary**
![image](https://github.com/Meeds-io/MIPs/assets/105866381/b9123ea8-9653-4ce4-84cc-d28684840126)

### Translation

_News_

- Display translation during the News consultation

_News list_

- Integrate the translation component into the News list title
- Allow emoji on the title of a news list
- Display translation on the content of the news list (article title, summary and cover) according to user language settings

_Stream_

- Display translation of the post for News (title, summary and cover) according to user language settings

### Expected Volume & Performance

Data volumetry will be changed since eventual metadatas will be stored for created notes.

### Extensibility 

The notes editor should be extensible in order to be customized for News case.

### Upgradability

- We should springify existing service & rest layers

### Existing Features

- A new "metadatas" button should be added for notes editor in order to open the metadatas drawer .
- The save button of notes editor should open the publication drawer in case of News creation.

### Access 
- GUI 

  - Metadata drawer should be implemented   
   
- API 

  - Content rest services should be cleaned after editor unification. 

### Services & processing
   - Notes services should be updated based on content services in order to store additional metadatas.
   - Content services should be cleaned after editor unification.

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds I have updated the description and added screenshots according to the last discussion. Ready to review for the functional part. @azayati ready to complete the technical part too.

**Comment by srenault-meeds** [comment]
Thanks @Julien-Dubois-eXo 

Feedbacks:

> All the metadata should changed according to the translation choice

Do you mean including banner?

> Cover name 

Cover looks like a wrong name as it is also used for newslist, and for news avatar in the activity. Can we use thumbnail instead?

> Mobile view: Not all edition options displayed:

We discussed about it and I thought that we minimize the effort to use only the options we have for SNV mobile view. Can we start that way for now? And then, we gather real feedbacks.

> Title

Make sure we can use emojis for news title please. We have made it available for notes few days ago.

**Comment by srenault-meeds** [comment]
> Cover name

I suggest _Featured Image_
Wordpress or Medium used that for their "banner / thumbnail / cover"

**Comment by srenault-meeds** [comment]
@Julien-Dubois-eXo Have you seen my previous comments?

**Comment by Julien-Dubois-eXo** [comment]
> All the metadata should changed according to the translation choice
> 
> Do you mean including banner?

Yes


> Mobile view: Not all edition options displayed:
> 
> We discussed about it and I thought that we minimize the effort to use only the options we have for SNV mobile view. Can we start that way for now? And then, we gather real feedbacks.

I just kept the options you asked for during the session but as you want. @margondicco is it fine for you?

> Title
> 
> Make sure we can use emojis for news title please. We have made it available for notes few days ago.

Ok

> Cover name
> 
> I suggest Featured Image
> Wordpress or Medium used that for their "banner / thumbnail / cover"

@margondicco you want the term cover. I let you answer. No objection from my side.

**Comment by margondicco** [comment]
> Cover name
> 
> I suggest Featured Image
> Wordpress or Medium used that for their "banner / thumbnail / cover"

no objection

**Comment by margondicco** [comment]
@Julien-Dubois-eXo could you update the image in the description ?

Thank you

**Comment by margondicco** [comment]
> Make sure we can use emojis for news title please. We have made it available for notes few days ago.

and summary please

**Comment by srenault-meeds** [comment]
ok @Julien-Dubois-eXo let me know once ready to review

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds ready to review

**Comment by srenault-meeds** [comment]
Hello @Julien-Dubois-eXo 

Thanks.

Feedbacks:
> Be able to add emoji on the title

And for summary ;-)

> After the first publication: we display a save button and no more publication drawer.

But can we update the publication once published?

Additional question:
_Do you plan analytics review to merge between notes / news?
Do you plan adding gamification items for using news, publishing it, getting the note read, bookmarked, etc.?
Regarding notification, is there anything planned? Indeed, notifications for news are for example deactivated by default for existing users_

**Comment by Julien-Dubois-eXo** [comment]
> And for summary ;-)

Yes it's planned. 

> But can we update the publication once published?

Yes as it's already the case by using the option dedicated to that in the 3 dots. 

> Do you plan analytics review to merge between notes / news?
> Do you plan adding gamification items for using news, publishing it, getting the note read, bookmarked, etc.?

It's not part of the scope for the moment. We will check the impact of the migration and see after that. 


> Regarding notification, is there anything planned? Indeed, notifications for news are for example deactivated by default for existing users

Some rework of news notification is planned. It will be descripted in the MIP dedicated to the publication.

**Comment by srenault-meeds** [comment]
Ok thanks. Go-Fonc

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds updated to include the rule about note/news creation with a same title 

> Be able to create a news or note with the same title, no matter the location on the treeview or the space

**Comment by srenault-meeds** [comment]
ok thanks!

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds FYI we will add a FF to unify the News editor with the Notes editor. The description was updated in that way.

**Comment by srenault-meeds** [comment]
> @srenault-meeds FYI we will add a FF to unify the News editor with the Notes editor. The description was updated in that way.

Why a FF? Why not improving it once for all?

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds to be able to correctly manage the delivery. At the end the FF we will be removed it as mentioned in the specification.

**Comment by srenault-meeds** [comment]
ok

**Comment by azayati** [comment]
@boubaker technical part ready to be checked.

**Comment by boubaker** [comment]
ok for me

**Comment by azayati** [comment]
ACCs & PRs ready for review (Meeds @boubaker @srenault-meeds)

**Comment by srenault-meeds** [comment]
Ok I'll do some checks. 

@Julien-Dubois-eXo Do you have any documentation about it please?

**Comment by boubaker** [comment]
> ACCs & PRs ready for review (Meeds [@boubaker](https://github.com/boubaker) [@srenault-meeds](https://github.com/srenault-meeds))

Thanks! a small comment on a PR https://github.com/Meeds-io/gatein-portal/pull/956#pullrequestreview-2295531221 to not affect globally the other pages.

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds here the documentation for the translation of an Article https://community.exoplatform.com/portal/g/:spaces:base_de_connaissances/base_de_connaissances/notes_1/26120

The article to announce the feature https://community.exoplatform.com/portal/dw/activity?id=442209

One note for the article and the properties https://community.exoplatform.com/portal/g/:spaces:base_de_connaissances/base_de_connaissances/notes_1/25831

Another note for the note and the properties https://community.exoplatform.com/portal/g/:spaces:base_de_connaissances/base_de_connaissances/notes_1/25920

**Comment by margondicco** [comment]
My feedbacks

1. UI Glitches on news only (ok for note) on the button translate

![une](https://github.com/user-attachments/assets/092d685a-1fa0-40fc-9b32-7a7755bab642)


2. Editor (news and note)
add an information on hover on the button properties

![deux](https://github.com/user-attachments/assets/61942f07-1467-47cc-abba-65b7f48f25fd)

3. illustration and summary lost when i create a new version

Only for a news
Create a news with an illustration and summary AND validate
Edit the news and create a new version
issue : the drawer property is empty


https://github.com/user-attachments/assets/0cc218d6-8668-4c11-a5d7-744d3c99973c



4. drawer favorites

add a news as a favorite. Open the page members or an other page but not a page stream
the label of the news doesn't display

![quetre](https://github.com/user-attachments/assets/1aef2005-0056-48b8-a982-227c2564c511)


it's ok if i open the drawer when i am on a page stream (general stream or a space stream)

cc @Julien-Dubois-eXo @srenault-meeds

**Comment by Julien-Dubois-eXo** [comment]
@margondicco my answers below:

1. First point, we do not reproduce it, neither on Meeds or eXo
2. We will add it in the next MIP.
3. It's the normal behavior without automatic translation. With automatic translation the featured image is reset also as it cannot be translated. It's a choice made to invite the user to check if it's the same image that should be used in different languages.
4. We reproduce it. The issue is displayed only when you open the drawer in specific pages. We will check why and fix it.

**Comment by azayati** [comment]
@srenault-meeds you can do your tests

**Comment by azayati** [comment]
> > ACCs & PRs ready for review (Meeds [@boubaker](https://github.com/boubaker) [@srenault-meeds](https://github.com/srenault-meeds))
> 
> Thanks! a small comment on a PR [Meeds-io/gatein-portal#956 (review)](https://github.com/Meeds-io/gatein-portal/pull/956#pullrequestreview-2295531221) to not affect globally the other pages.

@boubaker we have removed gatein-portal modification

**Comment by boubaker** [comment]
> > > ACCs & PRs ready for review (Meeds [@boubaker](https://github.com/boubaker) [@srenault-meeds](https://github.com/srenault-meeds))
> > 
> > 
> > Thanks! a small comment on a PR [Meeds-io/gatein-portal#956 (review)](https://github.com/Meeds-io/gatein-portal/pull/956#pullrequestreview-2295531221) to not affect globally the other pages.
> 
> @boubaker we have removed gatein-portal modification

Technically, all good for me, Thanks.

**Comment by srenault-meeds** [comment]
My feedbacks:
- Why do we need to save the notes or publish the news to add a translation?
This makes the UX bad for adding a translation.
I undertand that technically, we need to create version (this was done that way AFAIU) but this is a technical option we must not force to users IMO.
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/a1e7c542-8cfc-4e53-95b4-18582cb72069">

- Title:
When adding a long title, the news editor tells me it is still saving and the console lists an error 500
And I can't publish the news
For notes, I can't save anymore the note but I don't know why.
I suggest a limitation of the name length

<img width="944" alt="image" src="https://github.com/user-attachments/assets/314f6ed9-8202-4014-b72f-fa9fe7bf4cf3">

- Metadata: 
1. I can't see the featured image and the summary in the view mode
2. When editing I lose the featured image and the summary i have added
3. When reloading the page, I see back my featured image and the summary

- Summary:
No limitation to summary?
I suggest a limitation to avoid a bad display for reader . 
This is a summary right? And you know better than me, that redactors love writing
Suggestion: 500 char. max with a counter

- Draft:
1. Once I have saved the draft
2. I reload the page
3. A snackbar proposes me to drop my draft. 
Problem: I have no draft because I saved it

- Add translation
When adding a translation (using meeds), an error occurred it tells. Don't know what
<img width="350" alt="image" src="https://github.com/user-attachments/assets/0f904972-a758-4e70-8eea-ca3894d19826">

In the console, it tells the draft cannot be created
<img width="519" alt="image" src="https://github.com/user-attachments/assets/6f368342-0821-445f-8819-d5159d410239">

- Add translation
I lose my content incl. metadata
Not a good UX to help the user translating its content

- Going back to original version (from translation feature)
My content is empty. I don't feel confident with the feature.
It is ok when reloading the page.
Yet, it is really bad

- Display of notes
We lose the fact that the author and the date are listed.
See screenshot: 
<img width="729" alt="image" src="https://github.com/user-attachments/assets/aa5357e5-33fb-4fc9-8350-557f23912c36">

- Display of notes title once saved
The breadcrumb is not readable. We must ensure the previous pages are displayed and the current page name is truncated with elipsis

<img width="463" alt="image" src="https://github.com/user-attachments/assets/14d63add-3e09-446f-90e5-b806353b3cb9">

- Cannot publish once I have published my article
This makes the UX strange. I did have the chance to publish it but now it is no more possible.
At first, I thought it was a bug. But it is expected.
Still, I find it strange (mabe change reluctence)

- Three dots of a note
> UI revamping of the 3 dots menu
I don't see change of icons, neither of its size (must be 16px as discussed)

To think: the revamping and harmonization of Three dots of news:
-> missing icons

**Comment by azayati** [comment]
PRs to be merged:

- https://github.com/Meeds-io/social/pull/4012
- https://github.com/Meeds-io/content/pull/126
- https://github.com/Meeds-io/notes/pull/997
- https://github.com/Meeds-io/meeds/pull/2271
- https://github.com/Meeds-io/pwa/pull/19

**Comment by srenault-meeds** [comment]
My feedbacks was not a GO @azayati .

Some are blocking but I let @Julien-Dubois-eXo tell me how your team will copy with it

**Comment by azayati** [comment]
> My feedbacks was not a GO @azayati .
> 
> Some are blocking but I let @Julien-Dubois-eXo tell me how your team will copy with it

yes I will wait your go for merging, I have just prepared my PRs. But IMO the feedbacks are not blocking, I'm waiting and let u decide.

**Comment by srenault-meeds** [comment]
After discussing it with @Julien-Dubois-eXo, here is the prioritization:

**Blocking:**

_Title_
-> Limitation because error 500 
-> So limitation to 500 char. (after discussing it with @jdbois)
Suggestion: When reaching the 500 char., we cannot add more characters
To check if that can be edited afterwards using properties, or anything like that (no hardcording :) )

_Metadata (notes)_
-> I save a first version with no metadata
-> I add metadata, I save 
-> I save again the notes
-> I check the view -> No featured image/summary
-> I open the metadata drawer again -> It is empty
-> I need to reload the page to see the metadata back

_Notes Breadcrumb readability_
-> If long title, we can't see previous pages
-> The breadcrumb is not readable
-> Suggestion: Home visible -> Then other pages hidden by ... -> then the current page with elipsis if needed


**Not blocking. But to discuss for further improvement:**

_Translation_
-> Not possible to add translations until you save / post 
-> technical issue but we don't care about it. We need to address functional needs
-> When I want to add translations, I don't need to post an article, neither save the note

_Summary_
-> No limitation
-> Bad UX
Suggestion: Add a limitation for 1300 char. with a counter

_Draft Management_
-> Snackbar telling me there is a draft while I just saved the last version
Suggestion: review it outside the MIP

_Translation addition_
-> Content is empty 
-> I have to copy my content elsewhere to make sure I don't forget anything
Bad UX already reported for a previous MIP. To be reviewed later...

_Translation - Content is lost_
-> I add a translation version
-> I find the body empty
-> So I go back to the original version without adding any content for the translated version
-> My original content is empty

_Display of notes_
Ok understood. It is expected.

_Publication of News_
Ok, expected.

_Three dots of notes_
Font-Size To be updated later

cc @margondicco @Julien-Dubois-eXo I let you decide with your team

**Comment by margondicco** [comment]
Hello

My feedbacks @srenault-meeds 

Title => OK
Metadata (notes) => OK
Notes Breadcrumb readability => old issue we 'll fix this soon (MIP129)

Thank you

**Comment by azayati** [comment]
> Hello
> 
> My feedbacks @srenault-meeds
> 
> Title => OK Metadata (notes) => OK Notes
> 
> Thank you

@srenault-meeds you can validate these two points on ACCs

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds you can test the fix you have requested

**Comment by srenault-meeds** [comment]
Rationale added for history to understand why you have worked this MIP.
cc @Julien-Dubois-eXo if you want to update it, go ahead :)

**Comment by srenault-meeds** [comment]
Hello,

Title Limitation OK.
- Improvement: do not display the snackbar each time you open the note page
- Only when trying to add more characters

Metadata KO (for notes)
- Metadata keeps being removed
- Worst than before because event the refresh doesn't make the metadata back
- See GIF
![metadata note empty](https://github.com/user-attachments/assets/65e88f50-781a-4ad7-a17a-7dcf7d030fc5)

Other feedback to consider in the future IMHO:
<img width="1229" alt="image" src="https://github.com/user-attachments/assets/a3a52012-b8d9-4b60-b237-f6453bd179d7">

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds I do not reproduce both issues you are showing by following your steps. You need to show me to identify the specific steps.

**Comment by srenault-meeds** [comment]
> @srenault-meeds I do not reproduce both issues you are showing by following your steps. You need to show me to identify the specific steps.

Let's focus IMO on the problem of metadata.
The GIF is sufficient, isn't it?

@Julien-Dubois-eXo 

Thanks

**Comment by srenault-meeds** [comment]
Metadata for notes OK

GO @Julien-Dubois-eXo @azayati
