### ISSUE TITLE
PWA feature v1

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#134]
## Rationale

Meeds Hubs can be accessed using mobile browser. Fully responsive, the platform provides a mobile experience to its users.

However, end-users and market request to get an app to:

- list the app in the mobile stores
- receive push notifications
- ease the access to the platform (instead of leaving opened a browser tab)

Providing a native app came as a reference for a long time to reach these output. Yet, it requires:

- presence on both platform (iOS and Android). Thus, it duplicates the development efforts and therefore, we need different skill sets
- maintenability versus devices' versions

Progressive Web Apps (PWA) has emerged the last few years and it has been improved a lot to answer these concerns without losing native apps advantages:

- performance
- user experience
- push notifications
- store listing
- offline functionalities

Based on different reading, including [this one](https://www.directimpactsolutions.com/en/pwa-vs-native-apps-in-2024/#:~:text=While%20PWAs%20offer%20flexibility%20and,specific%20objectives%20for%20your%20application.)

### Top User Stories

**#### Installing the app from a browser access**
❓ Why?

This is one of the key option provided by PWA. It eases the process for users to add the app without looking for it. And product teams like it as it eases the process to reach users.

You share a link somewhere on the web
The user clicks to it, starts using it
He is invited to install the app
He receives notifications and maybe he will come back see the product again

💡 What?

When accessing the platform, and once logged in, suggest to install the app
![notif to install app](https://github.com/Meeds-io/MIPs/assets/58853195/26dafe50-56cc-4d1e-bf19-63eb9011125f)

Option still possible from the browser settings if needed
![install app from settings](https://github.com/Meeds-io/MIPs/assets/58853195/49f8029e-f8ae-429e-84f4-2a7d0e5caefc)

Same option can be proposed using desktop browser
<img width="99" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/135689ee-e57c-4816-966e-910041d61d2f">

Once installed, it is listed on the device as any other app
![App on device](https://github.com/Meeds-io/MIPs/assets/58853195/3c0da93a-02e9-46cc-b731-eccaaad10df6)

From the user settings, a user can scan a QR code from his user settings. Doing it install the app directly

**#### Branding**
❓ Why?

Theme, colors, logo, tagline can be added by administrators to make the platform identifiable for its community and users
It is highly expected by community leader to inheritate these items when installing the app
Users can also easily recognize their platform thanks to this

💡 What?
- Branding Favicon is used to create the app logo once installed
- Branding Mobile Name is used to label the app in the app list on the device (item to add on branding administration)

![App on device](https://github.com/Meeds-io/MIPs/assets/58853195/59eb6b56-b004-4f29-bc14-625761385ac9)

**#### Notifications**
❓ Why?
- Getting an app without receiving notifications is not relevant
- Indeed, notifications and push messages ensure users can get notified when needed, based on its preferences

💡 What?
-A new channel for notification is created to enable users to set their preferences "Mobile Notifications"
![browser notif pref](https://github.com/Meeds-io/MIPs/assets/58853195/2fa95168-3372-4a6f-9420-27888b9c6aad)

- Notification can be sent automatically to help the user accept
![notif authorization notif](https://github.com/Meeds-io/MIPs/assets/58853195/f9dd5e5d-fff1-4a6d-a47a-150a0997ac80)

- Notifications are sent 
![push notif](https://github.com/Meeds-io/MIPs/assets/58853195/a2229657-650e-42a8-8400-55a8808cc975)

- Notifications badge on device
![app avatar and notif](https://github.com/Meeds-io/MIPs/assets/58853195/c10b20b0-6ee5-4766-a4f2-ec6088f2f7e0)

**Precision: iOS users might not get notifications due to the fact that we recommend using a standard PWA background sync which is not support by safari, thus Apple
Same will happen to users which their default browser is Firefox**

🧐 Questions

We need to make sure notifications can be received even when the platform is provided in a secured and internal network (not public web)
**Precision: no use of google services like firebase is a must-have**

**#### User experience / Access to the platform**
❓ Why?
- Experience between mobile browser usage and PWA must be the same

💡 What?
- Make sure we can use the platform when using the PWA App
- Performance, access to options, to features must be consistent and checked

_More information [here](https://appinventiv.com/blog/migrating-your-website-to-progressive-web-app/)_

**#### Admin Options**
Admins can allow use of PWA or not for their users thanks to an Admin UI in the platform settings 

This UI suggests admin to:
- Enable PWA App installation for members
- Enable Notifications for members (to stop background sync)
- Configure Polling Sync (to allow them reduce of the network overhead)

We will study later using Push Manager API + alternative OSS push server solutions.

#### Gamification
NA

#### Notifications
- Notifications and push using [PWA technology](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Re-engageable_Notifications_Push)

#### Analytics
- Installation of the app (with device OS identification)

#### Unified Search
NA

### Expected Volume & Performance

The browser caches storage will be used to offer offline feature. Thus a browser caches consumption has to be monitored and cleaned when possible in order to decrease storage consumption.
The Browser navigation performances shouldn't be affected by PWA apps and offline feature, thus the service worker isn't expected to be used in a browser mode.

### Security 

N/A

### Extensibility 

The Manifest has to be dynamic and should inherit its properties from Branding Options and Public site as made on Deed Hub Card characteristics synchronization.
Each DAO Member has to be able to define its own Manifest by extension.

### Configurability 

| Property Name  | Default Value | Functional Behaviour |
| ------------- | ------------- | ------------- |
| pwa.backgroundSynchronization.period |  60 seconds | PWA Background Synchronization periodicity, value in seconds. This property will not be considered after the first startup since its value will be managed using a dedicated UI. |
| pwa.backgroundSynchronization.enabled |  true | PWA Background Synchronization activation. This property will not be considered after the first startup since its value will be managed using a dedicated UI |

### Upgradability

N/A

### Existing Features

The existing features shouldn't be affected by the PWA feature which will allow to install applications in multiple type of devices without changing existing features.

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
| pwa | true | ALL  | This flag will allow to enabled/disable PWA features. Use full especially to test the feature on production |

### Other Non Functional Requirements

  The portlets rendering has to change to use REST Endpoint in order to allow easily to handle offline mode of applications. This endpoint has to be available in each portlet Web Application.

## 3. Software Architecture

Knowing that this new feature will rely on previously existing feature, wome change will be brought again into product from previous commits:
- https://github.com/Meeds-io/platform-ui/pull/170
- https://github.com/Meeds-io/gatein-portal/pull/81
- https://github.com/Meeds-io/gatein-portal/pull/90
- https://github.com/Meeds-io/social/pull/386
- https://github.com/Meeds-io/gamification/pull/86
- https://github.com/Meeds-io/kudos/pull/45
- https://github.com/Meeds-io/perk-store/pull/24
- https://github.com/Meeds-io/wallet/pull/31
- https://github.com/Meeds-io/app-center/pull/174
- https://github.com/Meeds-io/meeds/pull/47

### Security

N/A

### Access 

  The offline mode has to be offered in applications by the new Page Layout Framework design and not application by application. Thus the fetch API will be polyfilled in order to add more features about background synchronization and periodic updates.
  A service worker has to be added in order to manage all types of content:
  - I18N resource bundles caching
  - Images
  - CSS
  - JS
  - HTML
  - REST calls

  The JS & CSS handling has to evolve to optimizing caching of resources. In fact, currently, when passing from a CI/CD version to another, all the JS & CSS & I18N resources are reloaded systematically. To avoid this and enahnce static resources caching, the Resources fetching has to evolve in order to retrieve the content using its MD5 content in URLs instead of a global assets version parameter.

### Services & processing

  The web notification channel or push notifications from Notification Service (will depend on Needed Fucntional Behavior) may be used in order to periodically retrieve the notifications to display in Application Badge (exactly same as Web Notif Badge by example) and the push/desktop notification content (same Image and content as the web notification by example).
  The same REST endpoint of Web notifications can be used this way to ensure the Background synchronization, even when the application isn't running.

### Data and persistence

N/A

### Clustering

N/A

### Multitenancy

N/A

### Integrations

N/A

### Migration strategy

N/A

## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts 
   - References

**Comment by rdenarie** [comment]
Hello
If we add a new channel for "Browser notifications", what about "Push Notifications" channel ?
Should we remove it ? keep it ? If we keep it, in which case it will be used ? 
As I understand, even you install from the playstore, you install the PWA, right ? So you will have "browser notifications".

If we remove "Push notif", for "Browser notif", it seems to be a simple "replacement", right ?

**Comment by srenault-meeds** [comment]
Yes indeed, this has to be studied. 
I didn't add any reference to push notif as we don't provide it with Meeds.
Still, it is a good question

**Comment by rdenarie** [comment]
I see 2 options : 

- bring push notif in meeds, and transform it in browser notif
- create a new browser notif, and drop push notif

You're right, to study

**Comment by srenault-meeds** [comment]
Will be worked later for now:

**#### Usage of service worker**
❓ Why?
- To enable offline access to platform and its content

💡 What?
- Provide a way so users can access the platform depending on their cache
- Once connected, their actions are updated

**#### Installing the app from a store**
❓ Why?
- Better audience reach & visibility. Users usually looks for an app using app stores.

💡 What?
- Google created the PWA technology. Thus, their playstore is PWA-friendly
- Process is the same: submit the app, pass all the requirements, publish the solution
- iOS is know as more restricted BUT change is coming and a tool like PWA builder can help us publishing our app to the App store. This tool can be used BTW to publish to any other app store.

_Informations [here](https://web.dev/articles/pwas-in-app-stores)_

🧐 Questions
If using different hubs, then how to manage it?
Suggested answer for now:
- No access to multi platform for now
- The option to install the app from the browser must answer these concerns

**Comment by srenault-meeds** [comment]
@margondicco to check please :)

**Comment by margondicco** [comment]
Hello ok for me

**Comment by boubaker** [comment]
IMO, no need to remove existing "Push Notifications" channel, we can replace it to be used even in Mobile App. We may need to support both type of notifications for a while until we replace completely the old Mobile Push Notifications with [PWA Push Notifications](https://docs.pwabuilder.com/#/home/native-features?id=push-notifications) coupled with [Background Synchronization API](https://developer.mozilla.org/en-US/docs/Web/API/Background_Synchronization_API)

**Comment by boubaker** [comment]
For the record and a possible code copying, the previous PRs to introduce PWA with its Manifest file and Service wokers on **6.1**:
- https://github.com/Meeds-io/platform-ui/pull/170
- https://github.com/Meeds-io/gatein-portal/pull/90
- https://github.com/Meeds-io/social/pull/386
- https://github.com/Meeds-io/social/pull/390/files
- https://github.com/Meeds-io/gamification/pull/86
- https://github.com/Meeds-io/kudos/pull/45
- https://github.com/Meeds-io/perk-store/pull/24
- https://github.com/Meeds-io/wallet/pull/31
- https://github.com/Meeds-io/app-center/pull/174
- https://github.com/Meeds-io/meeds/pull/47

Which was removed progressively in **6.5** since the feature wasn't enabled since a while.

Those PRs allow to have an offline feature and installable app but not [all of allowed features in PWA](https://www.pwabuilder.com/reportcard?site=https://webboard.app) (See below for features overview)

![Image](https://github.com/Meeds-io/MIPs/assets/594824/5678917a-1cf3-4559-9b09-2cf57303e8da)

**Comment by boubaker** [comment]
Ready for tech review by DAO Members (eXo: @rdenarie )

**Comment by rdenarie** [comment]
Hello
2 questions for me 

> TODO: Make JS œ CSS served with an id identified by its MD5 hash (determined when retrieved first time) instead of a common Asset version

Can you confirm that the md5 hash is computed from the content of the file, not from the filename ? 
So, if the content change between version, hash will change and cache will be invalidated.

> Notifications and push using [PWA technology](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Re-engageable_Notifications_Push)

Can you explain how push notifications will be sent ? In the link, I can see this : 

> Push is more complicated than notifications — we need to subscribe to a server that will then send the data back to the app. The app's Service Worker will receive data from the push server, which can then be shown using the notifications system, or another mechanism if desired.
The technology is still at a very early stage — some working examples use the Google Cloud Messaging platform, but are being rewritten to support [VAPID](https://blog.mozilla.org/services/2016/08/23/sending-vapid-identified-webpush-notifications-via-mozillas-push-service/) (Voluntary Application Identification), which offers an extra layer of security for your app. You can examine the [Service Workers Cookbook examples](https://github.com/mdn/serviceworker-cookbook/tree/master/push-payload), try to set up a push messaging server using [Firebase](https://firebase.google.com/), or build your own server (using Node.js for example).

We need 2 things : 

- Know WHERE notification are sent (i.e. not google or extra territorial server)
- Customer with onPrem can you his own push notification without use eXo Credentials.

**Comment by boubaker** [comment]
> Can you confirm that the md5 hash is computed from the content of the file, not from the filename ? So, if the content change between version, hash will change and cache will be invalidated.

Yes, I confirm as described below (the TODOs was just notes that wasn't dropped after writing the tech spec, I dropped them, please refer to the content for more details)
 
> Can you explain how push notifications will be sent ? In the link, I can see this :

As described, in fact the background synchronization with a periodic synchronization will be used, which will retrieve data from server instead of a push notification sent from server side (like a long polling VS websocket, it will not be real time, but happens to be more easy to parameter by user and to maintain).

> We need 2 things :
> 
> * Know WHERE notification are sent (i.e. not google or extra territorial server)

Not sent anywhere, just polled by client periodically

> * Customer with onPrem can you his own push notification without use eXo Credentials.

Yes

**Comment by rdenarie** [comment]
Long polling for notifications brings a lot of question : 

- Volumetry : 1 request by user by minute. It will increase the traffic to exo. 
- Does this request will be done with the user session ? if yes, does it will maintain his session up (which is by default 30 minutes)
- What about notifications when the application is not running on the phone ? How it works when application runs in background ?

You take the choice to no implement push notification but long polling. Can you explain what are problems with a real push notifications system ? I think you take time to evaluate this, can you share the pro and the cons ?

Thanks for you answers

**Comment by boubaker** [comment]
> Long polling

**No long polling** in fact. It's just a comparaison (Server Push information VS Client Side Retrieve mechanism). The long polling is very expensive thus not relevant at all.

> Volumetry : 1 request by user by minute. It will increase the traffic to exo.

Yes, one request per minute by example or configurable if needed so that switch installation and users count. For an installation where we have a b ig number of users, we may even need to decouple notification server from Monolith but we don't have such a need for a such architecture for now.

> Does this request will be done with the user session ? if yes, does it will maintain his session up (which is by default 30 minutes)

Yes, like Web Notifications Rest calls in fact, it will not differ from any other fetch mechanism. As said, for big installations, we may need a dedicated architecture where we can design a dedicated server that handles the notifications and which may even be fully stateless with a dedicated authentication tokens using JWT by example. But for now, I think we just need to keep it simple in order to work on features more than volumetry.

> What about notifications when the application is not running on the phone ? How it works when application runs in background ?

See details [here](https://docs.pwabuilder.com/#/home/native-features?id=push-notifications):
> ...regardless of whether or not your app is currently running.

See my previous comment : 
> IMO, no need to remove existing "Push Notifications" channel, we can replace it to be used even in Mobile App. We may need to support both type of notifications for a while until we replace completely the old Mobile Push Notifications with [PWA Push Notifications](https://docs.pwabuilder.com/#/home/native-features?id=push-notifications) coupled with [Background Synchronization API](https://developer.mozilla.org/en-US/docs/Web/API/Background_Synchronization_API)

**Comment by rdenarie** [comment]
Ok, it is clearer. 
You will use the Background Synchronization API, which is an experimental API, not implement by Firefox for example. 

About the fact that the session is maintenained by the mechanism, @margondicco @srenault-meeds can you confirm it is not a problem (functionnaly speaking) for you ? 
A user with pwa app installed, will be "never", disconnected from the platform (except perhaps when the server restart). His session will never expired as we will have at least one request by minute, which will refresh the session

**Comment by boubaker** [comment]
> will be "never", disconnected

Not really, in fact the "Who's online" widget works with a different mechanism and the user will be disconnected in some special cases where it will need to reconnect by opening the app and login again.

**Comment by srenault-meeds** [comment]
> can you confirm it is not a problem (functionnaly speaking) for you ?

No problem for me 🙂

**Comment by margondicco** [comment]
Hello @boubaker 

for this

> Yes, one request per minute by example or configurable if needed so that switch installation and users count. For an installation where we have a b ig number of users, we may even need to decouple notification server from Monolith but we don't have such a need for a such architecture for now.

For you, what is a big volumetrie ? 5k users ? 15k users ?  I know it's just a projection but an important point. 

My 2 pieces : 

Our benchmark for a standard installation (without cluster for example) is 8k to 20k users (1000 to 1500 simultaneous users) Could it be compatible ? 

For example, a community manager could publish an activity (short message or news) for all the members. So in the same time, 8000 notifications could be sent.

Thank you for your feedback

**Comment by margondicco** [comment]
Hello @rdenarie 

> About the fact that the session is maintenained by the mechanism, @margondicco @srenault-meeds can you confirm it is not a problem (functionnaly speaking) for you ?
> A user with pwa app installed, will be "never", disconnected from the platform (except perhaps when the server restart). His session will never expired as we will have at least one request by minute, which will refresh the session

Functionnaly speaking it's not a problem. It might be interesting to ask a relevant customer about this. I'll take the point

**Comment by boubaker** [comment]
> For example, a community manager could publish an activity (short message or news) for all the members. So in the same time, 8000 notifications could be sent.

Shouldn't be a problem, either having 8 K or 8 M notifications, the rate will be dependent on users who had installed the application using PWA shortcut. Thus, we may have for a single user three devices: Mobile + Desktop + a tablet and thus the same user will ask the server for updates 3 times a minute. At the same time we may have users that doesn't have installed the application using PWA, thus no check for updates. But if we keep an hypothesis that for each user in a database we will have at least 1 PWA installation, thus we will have (for 20k **active users** in database), **20k requests** per minute => 333 req/s. The throughput seems high but if we consider that each request will take in average between 150ms and 200ms (endpoint `/portal/rest/notifications/webNotifications`), we will have to simultaneously be able to server 333 / 5 = 66 simultaneous requests for PWA in the worst case.
This is just theoretical, but I think we will need to make a benchmark workshop to test it and ensure that it's ok. For my part, we are already working on Multitenancy & Microservices preparation, we may need this first use case to allow Microservice deployment if it comes to deploy for more than 20k active users (I know that some concrete use cases, we may reach a million and a half).
In order to ensure a good quality of service in some special deployments, the Microservice architecture may need to be coupled with the clustering strategy as well.
But, before going deep in Global Architecture planning, let's keep it simple and choose either to delegate this complexity (using firebase based push notifications) or to manage it by our own means. For my part, I proposed here to keep both strategies and experiment the PWA Push notifications, then progressively deprecate the used Push Notifications through firebase when we would be ready to fully support the new PWA Push notifications.

**Comment by rdenarie** [comment]
Currently, I have objections on this MIP. My concerns are mainly about notifications. In my points I will use "Poll Notifs" versus "Push Notifs" to speak about the 2 systems

- Firstly, the load. Poll notifs require that each user with PWA applications installed and with notifications activated make request on regular basis (default 1 minute) to get new notifications. Nevermind the number of concerned users, it will generate a traffic to the server. In case of customer with lot of user using PWA app, the traffic can be huge, and will potentially required to increase server resources (eXo server, or additional server in case a dedicated server). 
As in all "poll" system, a very small part of theses requests will return a notification. For the major part, the answer will be : "no result". 
So we are introducing a feature generating a non negligeable compute on the server, for which the ratio of relevant request vs non relevant request is very low
By comparaison, push notification will only send information to the user when a notification is available. Only necessary requests are used. So even if it could request an additional server/container to do that, it will use less ressources than something dedicated to a poll system.

- Secondly, the user session. As I understand, if the PWA application make a request each minute, it will maintain the HTTP session alive on the server. By default, the HTTP session have a 30m life time, that we will never reach because of notification request. Having http session which never expire implies :
  - Constant resource usage (memory mainly)
  - Security issues : it is not a good practise to have an infinite session
- Finally : Background API is only supported by Chrome and Edge, not by Firefox and Safari. So I'm not sure it will work on IOS  

After discussion with @margondicco, PWA application should bring a lot of user to use the PWA app, on mobile AND on desktop. So questions about resources WILL be important quickly, even if we suppose that it will concern only users which have installed the app AND which activate notifications.

So my proposition is : 
study the usage of a real push notification system, with the objectives to determinate pros and cons of this solution, in order to compare with the one you propose here, so that we have all informations to take a completly informed decision.

**Comment by plamarque** [comment]
trade-off agreed to address @rdenarie concerns on this MIP : 
- Add an admin UI in Platform Settings to allow enabling/disabling not only PWA support but also notification support (would stop background syncs)
- the sync interval would also be configurable to allow admins reduce of the network overhead

further work may be done later to study a using Push Manager API +  alternative OSS push server solutions.

**Comment by srenault-meeds** [comment]
Description updated accordingly

**Comment by boubaker** [comment]
> Description updated accordingly

Properties list updated as well for default value to be used in first run with this feature.

**Comment by rdenarie** [comment]
Hello,
As discussed in the meeting :

- Ok to start the solution based on Poll Notifications with these new properties. 
- We will need to study the behaviour of the feature in term of server load when installed
- We confirm that Notifications in PWA will be NOT available for IOS and Firefox users

**Comment by boubaker** [comment]
> Hello, As discussed in the meeting :
> 
> * Ok to start the solution based on Poll Notifications with these new properties.
> * We will need to study the behaviour of the feature in term of server load when installed
> * We confirm that Notifications in PWA will be NOT available for IOS and Firefox users

Sure, this will be to avoid compleixfying the installation for now and at least start supporting PWA with a set of features. The support of further features like "Push Manager" can be considered in a dedicated MIP where we will take time to compare alternatives to firebase.

**Comment by srenault-meeds** [comment]
Indeed and already identified in the description as well

**Comment by margondicco** [comment]
Hello i have one objection

my first early adopters :
IOS device important 50% of the end users
Desktop : firefox is the browser by default

**Comment by srenault-meeds** [comment]
I understand your point. 
However, as detailed above in previous comment: 
- we will provide an Admin UI to enable or not the PWA + notification support configuration
- this might help your customers to disable this PWA app in case it is not relevant

AND as you might know, this PWA won't be able to replace in one shot the current native mobile app you have. It will be done step by step.

My recommendation (and the one discussed above) is: we start and we see how it goes. Only firefox and safari are not supporting nowadays the background sync API FYI

**Comment by boubaker** [comment]
After study and elaboration of a first PoC, the Periodic Background synchronization seems not to be relevant to notify users since the trigger between two invocations is very high:
> If undefined, these are set to 43200000, which is twelve hours in milliseconds

https://wicg.github.io/periodic-background-sync/index.html#minimum-periodic-sync-interval-across-origins

Thus, not possible to  make a generic solution for Push Notifications without FCM, like asked in Func Spec
> no use of google services like firebase is a must-have

Consequently, we will need to use Push Services as provided by browsers (read more about this [here](https://pushpad.xyz/blog/customize-the-browser-push-service), [here](https://web.dev/articles/push-notifications-how-push-works#who_and_what_is_the_push_service) and [here](https://pushpad.xyz/blog/what-are-the-browser-push-services) by example)
> Each browser can use any push service they want, it's something developers have no control over.

> * Mozilla autopush for Firefox
> * Google Firebase Cloud Messaging (FCM) for Chrome (and some Chromium-based browsers like Brave, Opera, etc.)
> * Windows Push Notification Services for Edge
> * Apple Push Notification service (APNs) for Safari (at the time of writing Safari still uses a proprietary technology, not the standard)

**Comment by boubaker** [comment]
Meeds PRs:

- https://github.com/Meeds-io/gatein-portal/pull/941
- https://github.com/Meeds-io/commons/pull/628
- https://github.com/Meeds-io/platform-ui/pull/812
- https://github.com/Meeds-io/social/pull/3968
- https://github.com/Meeds-io/layout/pull/174
- https://github.com/Meeds-io/analytics/pull/206
- https://github.com/Meeds-io/gamification/pull/1690
- https://github.com/Meeds-io/gamification-github/pull/189
- https://github.com/Meeds-io/gamification-twitter/pull/93
- https://github.com/Meeds-io/gamification-crowdin/pull/46
- https://github.com/Meeds-io/kudos/pull/514
- https://github.com/Meeds-io/perk-store/pull/338
- https://github.com/Meeds-io/wallet/pull/541
- https://github.com/Meeds-io/app-center/pull/350
- https://github.com/Meeds-io/poll/pull/161
- https://github.com/Meeds-io/content/pull/192
- https://github.com/Meeds-io/notes/pull/1051
- https://github.com/Meeds-io/deeds-tenant/pull/79
- https://github.com/Meeds-io/task/pull/411
- https://github.com/Meeds-io/pwa/pull/9
- https://github.com/Meeds-io/meeds/pull/2300

**Comment by boubaker** [comment]
Ready for Review by DAO Members. ACC Meeds up to date with PRs added here:
https://github.com/Meeds-io/MIPs/issues/134#issuecomment-2250887610

Some changes are required on eXo package, like deleting Skin & JS Services made in ECMS or adapt the SkinService to make it work with the new enhanced behavior of SkinService & JavascriptService. (The modification was made to make the Resources caching more efficient and less memory consuming for end user browser when dealing by not updating the version only when the content of JS or CSS file changes effectively)

**Comment by rdenarie** [comment]
Hi,
I test the feature today, and I make adaptations on eXo side.

Two remarks for you  
- I add a fix on gatein-portal module. I add it in feature/mips and in your merge pr. I let you check it
- I have some warning in my server console (a lot of): 

> 
2024-08-13 18:36:31,014 | WARN  | Cannot load and merge the bundle: locale.portal.services [org.exoplatform.services.resources<http-nio-0.0.0.0-8080-exec-8>] 
2024-08-13 18:36:31,016 | WARN  | Cannot load and merge the bundle: locale.portal.custom [org.exoplatform.services.resources<http-nio-0.0.0.0-8080-exec-8>] 

Have you this on your side ?


I have a last point to address on exo side tomorrow, and after that, it will be ok to merge.

**Comment by rdenarie** [comment]
Hello,
I finish to test and apply modifications on eXo side.

after ansering my two remarks, you can proceed to merge

**Comment by rdenarie** [comment]
Exo PR : 
Commons-exo : https://github.com/exoplatform/commons-exo/pull/45
ECMS : https://github.com/exoplatform/ecms/pull/2384
Jitsi : https://github.com/exoplatform/jitsi/pull/136
digital-workplace : https://github.com/exoplatform/digital-workplace/pull/141
platform-private-distributions : https://github.com/exoplatform/platform-private-distributions/pull/380

Pr to add PWA notifications : 
Chat : https://github.com/exoplatform/chat-application/pull/761
Web conferencing : https://github.com/exoplatform/web-conferencing/pull/326
Documents : https://github.com/exoplatform/documents/pull/1287
DLP : https://github.com/exoplatform/dlp/pull/57
Processes : https://github.com/exoplatform/processes/pull/382
Agenda : https://github.com/exoplatform/agenda/pull/683

**Comment by boubaker** [comment]
> I add a fix on gatein-portal module. I add it in feature/mips and in your merge pr. I let you check it

Thanks, I see, the `/` was missing at the end of context paths.

> I have some warning in my server console (a lot of):

Not related to the MIP (reproduced on develop as well, see [this](https://github.com/Meeds-io/gatein-portal/pull/943/files#diff-1534cdbd48eee511c94418f50a8afca23be020057ace8077ed69cede7698dbb6) and [this](https://github.com/Meeds-io/gatein-portal/pull/943/files#diff-90f8af3946d4f33060c5437059f2ad31241a87bd7a277c68081d3de619aeac98)). it seems that those files was removed from sources. I will open a dedicated issue on it and consider fixing it apart.

> Exo PR :
> Commons-exo : https://github.com/exoplatform/commons-exo/pull/45
> ECMS : https://github.com/exoplatform/ecms/pull/2384
> Jitsi : https://github.com/exoplatform/jitsi/pull/136
> digital-workplace : https://github.com/exoplatform/digital-workplace/pull/141
> platform-private-distributions : https://github.com/exoplatform/platform-private-distributions/pull/380

There isn't an implementation of Push Notification Messages Plugin (like [here](https://github.com/Meeds-io/pwa/pull/9/files#diff-9cc0dc1960d7b5a90e0326d217965dabcec0ccf2e5315595128c4a0e1c41a639R65)). Would you like to disable push notification messages on eXo Addons ? (Default behavior is to display a I18N key, which is useful for dev mode only but I think it would be better to disable it when no plugin implemented)

**Comment by rdenarie** [comment]
eXo Prs are ready. You can proceed to merge. 
After that, I'll merge exo pr

**Comment by boubaker** [comment]
Merged to develop
