### ISSUE TITLE
Pin an activity

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#14]
## Rationale

Details of the GAP ( problem(s) to address ) expressed by few words using some screenshots.

Some of the space hosts need to hilight activity for their space. The problem is that it can be done currently and important message cannot be easily identified.
While it needs to be for example read by all the members, etc.
Same thing when a new comer to the space discovers the community, it could be nice to check what's to know first.

So the idea here is to propose to space host or redactor when identified to pin an activity to the top of the space stream.

## 1. Functional requirements
- A space host or a redactor of a given space can pin/unpin an activity to make it displayed on top of the space activity stream
- The button pin/unpin will be displayed in activity menu for a manager/redactor of a space only
- A pinned activity might be easily identified so users can see it right away
- More than one activity can be pinned in a space

Design for information: https://xd.adobe.com/view/66d1a30d-2e41-4557-b4a0-dd1464e13fd7-3382/screen/5fce51b6-df31-4a7a-b17f-b6761bf78495/

- This feature has to be disabled by default and enabled through a property (Feature flag): Set to false by default - exo.feature.PinActivity.enabled

- In the future, it can be useful to propose a pinned activities list in the general stream so it is easy to check what's in the spaces I am member of. Here are the informations to be displayed in this list:
-- Activity / activity-type (poll, challenge, note, activity, etc.)
-- Space where this has been posted initially
-- Author of the activity to know who has posted this initially
-- Date of the activity
This list should be sorted by the time it has been pinned. Meaning that if I pin an activity today, on September, 5th while the activity has been posted two months ago, this activity will be displayed in the first position in the list. That way, hosts and redactors will have easy ability to order the pinned activities list.

For now, activityAuthor will be displayed in the pinned activities to hilight contributions from any members. 

In the future obviously, after some usage, it could be interesting to add settings for this portlet so the admin can decide to change the sort of the pinned activities (pinDate, activityDate) and to change the display of authors for communication policies (display the pinAuthor instead of the activityAuthor). For example, when the author is not active anymore in the platform neither in the organization.

For your informations, notifications won't be sent when activity is pinned, but it would be interesting to have this information in addition to the pin author so the notification receiver understand who has done this action.

![pinned activities in the stream](https://user-images.githubusercontent.com/58853195/188127578-b36cd8f8-e4f0-4748-a12b-5bc41758087c.jpg)

### 2.1. Performance requirement
The stream rendering has to be as performant as current rendering performances. This means, we shouldn't change the number of RDBMS queries nor computing in Service layer.
### 2.2. Security requirement
Only space redactor or manager can pin or unpin an activity. If an activity is pinned by a manager/redactor, any other manager/redactor can unpin it or replace it by another pinned activity. The fine security check will be made on Service layer only with a 403 HTTP response code when user is not allowed.
### 2.3. Extensibility requirements
The display of the pinned activity(ies) has to be made in a dedicated Vue component that has to be extensible (without having to redefine the whole activity stream component).
### 2.4 Configurability requirements
We have to allow to pin multiple activities through a system (or exo.properties) property. The default value of allowed activities to pin will be 1.

### 2.5 Feature Flag (property name, default status, target audience, functional behaviour)
A feature flag is applied for the feature. And FYI, as soon as the feature is available in develop, then a flag will be set to true by default (`exo.feature.PinActivity.enabled`):
- meeds package: set to true by default
- others: set to true by default
That way, if other (i.e eXo) wants to disable the feature by default, that won't change the meedslab way to deliver features.

This feature includes:
- ability for hosts and redactors to pin activities in their space
- ability for users to filter their general stream by pinned activities
- ability for analytics admin to know the usage of pinning an activity

## 3. Impacts
- #### Documentation to update
- #### Feature flag to false by default

### 4.1. Security
The REST endpoints to access activities will remains as it is and doesn't need to be changed with an additional security check.
The new endpoints that will allow to pin/unpin activities has to consider user role inside the space to make a security check in Service layer.. The REST endpoints has to be accessible to all internal users (no external user is allowed).
### 4.2. REST API
Two endpoints has to be developed for pin & unpin operations.

The URL of REST endpoints are :

- **POST** /portal/rest/v1/social/activities/{activityId}/pins : to pin an activity
- **DELETE** /portal/rest/v1/social/activities/{activityId}/pins : to unpin an activity

The Activity DTO has to be modified to add:

- `pinned` boolean attribute to indicated whether the activity is pinned in activity stream of space or not
- `pinDate` String attribute with ISO8601 Date format for date of pin

When the user pins an activity on a space that have already reached the maximum pinned activities, a **HTTP 400** response code with text error message (`maximum_pinned_activities_reached`) will be used and the user has to add a query param `replaceOlder=true` to confirm replacement.

### 4.3. Services & processing
The statistics collection has to be made on pin/unpin activities with the author identity id and date of pin.

#### 4.4.1. Macro data model
The following fields will be added in existing Activities Table :
![image](https://user-images.githubusercontent.com/594824/188262949-a0efbd1c-413e-434c-9d30-80962c29fd4d.png)

- `PINNED`: a **Boolean** attribute to indicate whether the activity is pinned or not
- `PIN_DATE`: a **Timestamp** of pin operation (should be null when unpinned)
- `PIN_AUTHOR_ID`: a **Long** attribute for the AUTHOR identity identifier (should be null when unpinned)

#### 4.4.2. Cache management
The activity and space stream activity ids has to be purged when an activity gets pinned or unpinned.
#### 4.4.3. Persistence layer
The Query of retrieving the activities of a space (get activities by owner) has to be modified in order to retrieve the list of activities by the following orders :

1. `ORDER BY activity.pinned DESC`
2. `ORDER BY activity.pinDate DESC`
3. `ORDER BY activity.updateDate DESC`

This will ensure to retrieve the pinned activities in top of retrieved activities list inside space activity. (that will can be used as feature inside the main activity stream)

**Comment by rdenarie** [comment]
Hello,
As discussed in technical commitee, I have only one remark on this :
As described functionnaly, the pinDate and the pinAuthor seems not necessary. 

For the date, one possibility to use it functionnally, is the "replaceOlder" scenario : in the case the max pin activity is reach, and replaceOlder=true, I replace the older pinned activity. 
So we need to confirm the functionnal behaviour for "Replace Pin". In function of that we could decide if it is preferable to keep or not the date.

About the Pin_Author, as I can see, it seems not used too. To keep the implementation as simple as possible, I prefer to not use it. 

For the rest of the MIP description, I'm ok with this MIP

**Comment by srenault-meeds** [comment]
Hello,

On a functional point of view, pinDate and pinAuthor could be interesting if in the future, we propose to sort the pinned activities upon these properties (instead of activityAuthor or activityDate)

Regarding the replaceOlder, for now, we will accept only one activity to be pinned by space but in the future, that can evolve with a slider on top of the stream like it is done in facebook for example. 

I will let @boubaker reply to you properly regarding these remarks if needed.

**Comment by rdenarie** [comment]
Even if theses property could be interesting in the future, if the current development do not need it, it is not necessary to increase the dev complexity. 
We could add them when we need it.

**Comment by boubaker** [comment]
Knowing that the development complexity is very minor here the fact to add the date & author (we will use a dummy setters on a JPA entity object without further Service processing), I think it could be better to keep them.
As discussed, the advantage of having them is that, this kind of information can't built on old existing data (we will loose the pinDate & author information if it's not stored at the time of pinning). So, if in the future we will want to display the list of pinned activities in the main stream (which is in the pipe of future features as @Samuel-Renault-eXo said), we will not be able to display the list of pinned activities switch its pin date (of course, we can't use activityDate because it's not pertinent IMO in context of list of pinned activities view).

To have a more analytic view of this proposition of having those fields by default or not : 

* Pros
  * Better functional **flexibility** with reduced dev effort and reduced data footprint
  * **Avoid loosing** data information that can't be rebuilt in the future (the pin author and date can't be rebuilt if not collected at time of pinning)
  * **Avoid** having to make a **data migration** or a **complex development** due to lack of those information in existing activities data
* Cons
  * Having additional instructions to execute when pining an activity (use `setPinDate` and `setPinAuthorId` when persisting pinned activity, which doesn't require a specific nor a complex business logic)
  * Having an additional data to persist on pined activities (which is reduced by the fact that it will be stored only on 1 activity at most per space)

**Conclusion**:
I think we will have more things **to win** when applied (and **to loose** if not applied) more than things **to economize**.
To know if it's better to apply it or delete those fields, I think that the only one who will be able to answer that is @Samuel-Renault-eXo (Functional architect of the solution). @Samuel-Renault-eXo , do you : 
1. think using those information (Pin author & date) will be used in future extended functionalities of current feature
2. know that those information will not serve at all for future extended functionalities of current feature
?
I let you decide whether to keep it or not. If useful, it would be better as @rdenarie said, to add the possible usage of those fields in functional requirements (or non functional requirements, in extensibility section by example) with this proposition, by example: << We will need to keep the pin author and date in pinned activity in order to reuse them for future usages >>. This will explicit more the need behind adding those fields IMO.

**Comment by srenault-meeds** [comment]
Hello, thanks from both for your functional feedbacks. I agree that pinDate is needed as it will be use as the criteria to sort pinned activities in the agreggated list to be displayed in the general stream. 
And in addition, we might need to display pinAuthor instead of activityAuthor for communication policies purpose ("the communication service holds this ability only", "UserAlpha is not a platform's user anymore, we don't want to display its name in the general stream", etc. To conclude, this info can also be needed for the notifications to be sent each time an activity is pinned.

I have updated the description to clearer the questionning. Hope that helps, if not, let's discuss it in the product committee. Thanks

**Comment by rdenarie** [comment]
Ok for me.

**Comment by srenault-meeds** [comment]
Added the part regarding the feature flag
