### ISSUE TITLE
Top Navigation

### ISSUE THREAD

**Issue by mzorai** [Meeds-io/MIPs#36]
## Rationale

- Need to highlight important pages
- Need to structure access to these pages 
- sub pages are not displayed in the left navigation

### Navigation portlet on top bar

- Add a new navigation portlet which appears in the top bar
- By default, the navigation portlet should display the current site's navigation into the navigation portlet
- Permissions : platform/users 
- The Navigation portlet should display at first the parent node followed by sub nodes
- If there is no subnode, the portlet isn't displayed
- The node which does not contain a page will open sub sub nodes i.e. the third level of nodes in a dropdown menu
- If a user is not granted the permission to view one or more nodes of the navigation portlet (which displays site's root node tree), the node shouldn't not appear
- The new navigation portlet should display all clickable pages (i.e. those opening a page) and pages grouping (i.e. those not associated to a page) with a dropdown icon allowing to switch between sub pages
- The navigation menu should be responsive: In mobile views, it appears in bottom of the page
- Depending on screen resolutions, we should display an arrow in the right of the navigation allowing to navigate to all the nodes
- When scrolling to the most right, an arrow in the left should appears allowing to navigate back to first nodes of the navigation

Link to design: 
Desktop : https://xd.adobe.com/view/55025386-7a36-4347-a725-4e138c0c6ea7-0051/
Mobile : https://xd.adobe.com/view/7f7d3849-82b4-4cd8-a239-0058d3524b29-2a2e/

### Settings 

In the branding portlet 

Add a switch button : "Activate the top bar navigation"

Wihtout UI 
- Site selected
- template : Top bar navigation template preselected
- Root node of the selected site

### Security 

Only authenticated users can see the menu
User can only see only pages that he is allowed to see.

### Feature Flags

Add a feature exo.feature.navigationPortlet.enabled, default to false i.e. do not display the feature until it is possible to manage the node to appear in the portlet

Property name: exo.feature.navigationPortlet.enabled
Default value: False
Target Audience: platform/users 
Functional behavior: Hides the new navigation portlet until the implementation is done and validated, removed when the feature is fully validated

### Other Non Functional Requirements

Vue and Vuetify should be used for the new portlet.

### Security

In REST APIs, we will have to use @RolesAllowed to restrict access to endpoints to only allowed users .

### Access

- GUI
  - A new Vue Portlet should be added for the new Menu
  - The branding portlet should be updated by adding the switch that will show/hide the navigation portlet.
  - All components will be added under a new folder named "top-bar-menu" added to the Social webapp package under "/webapp/portlet/src/main/webapp/vue-apps"

### Services & processing
   - Navigation rest API will be used to get the current site nodes in the setting drawer
   - Navigation rest API should be updated to be able to get children of a specific node
   - A new Navigation setting API should be added to store/get the new Navigation Menu setting (list of nodes to show in the portlet)
   - A new service to manage the menu settings should be added in the social service packages (location to be defined),
 this service should use the org.exoplatform.commons.api.settings.SettingService to store/ get the Menu settings:
     - To store nodes:
                   settingService.set(Context.GLOBAL, Scope.APPLICATION, "topBarNavigationNodes", new SettingValue<String>(navigationNodes));
To get nodes:
                   SettingValue<String> navigationNodes= (SettingValue<String>) settingService.get(Context.GLOBAL,   Scope.APPLICATION, "topBarNavigationNodes");

     - Setting service for this version of the portlet will only store the value of the switch (added to the branding portlet)

### Data and persistence

Menu settings should be stored in the Global Settings data so need for new tables.

**Comment by mzorai** [comment]
MIP eXo https://community.exoplatform.com/portal/g/:spaces:exo_product_management/exo_product_management/notes/21898

**Comment by rdenarie** [comment]
go tech needed @boubaker

**Comment by rdenarie** [comment]
I have some questions : 

- if a node is not associated to a page, but have sub nodes : what happens when I click on the node title ? what happens when I click on the arrow ?
- if a node is associated to a page, and have sub nodes : what happens when I click on the node title  ? what happens when I click on the arrow ? 
- if a node is not associated to a page, and have no sub node, what happens ? Does it appears ? Can I click on it ?
- What about SYSTEM nodes ? HIDDEN nodes ?
- What is displayed if the user hasn't the right to see any page ?
- Who can edit the portlet configuration ?
- Where the portlet will be positonned ? dynamic container  ? in the top bar itself ? how it will be added in the portal ? can you describe for new customer ? for existing customer which migrate ?

cc @mzorai @mkrout @azayati

**Comment by margondicco** [comment]
Hello my feedback in french because i'm tired :-)

sur la MIP36 , besoin IMO d'éclaircir le sujet "defaut settings"
On ne va pas avoir de fonction d'édition des paramètres en ligne
 
Pourtant a terme, nous aurons besoin d'autoriser un admin à choisir le noeud root et de choisir parmis une liste de template. IMO il faut donc prévoir déjà la structure de données permettant cela.
 
Pour la V1 on a un seul template et ce sera nécessairement le noeud root du site dans lequel est positionné cette portlet
 
Enfin, le sujet migration est à aborder pour répondre à l'attendu suivant pour eXo : 
On ne doit pas intégrer automatiquement cette portlet pour les clients existants.

IMO on évite la logique dynamic contener pour sa mise à disposition
 
Merci pour vos retours

**Comment by srenault-meeds** [comment]
Hi, feedback noted while reading the MIP:

> The navigation menu should be responsive: In mobile views, it appears in bottom of the page

How would you manage this? If more than 4 items, horizontal scroll OR max 4 items and if more than 4, then 3 items then a see more button to access other items.

How would you manage subnodes display when using mobile? 
Please make sure to check UX expertise regarding tab bar. 
Check this please: 
https://uxplanet.org/how-to-design-a-better-bottom-navbar-5127c8b8102f
https://medium.com/lifes-a-picnic/5-steps-to-design-a-tab-bar-the-right-way-b800005691c

> Depending on screen resolutions, we should display an arrow in the right of the navigation allowing to navigate to all the nodes

I would not recommend this behaviour as it is really not a good UX when using a small screen resolution. A see more would be more efficient and useful.

> if a node is not associated to a page, but have sub nodes : what happens when I click on the node title ? what happens when I click on the arrow ?
if a node is associated to a page, and have sub nodes : what happens when I click on the node title ? what happens when I click on the arrow ?

Same wondering

> UI comment
Please can we add padding between the label and the caret so it is more accessible and more balanced?
And please can we make sure the dropdown will have same width of the tab itself?
<img width="194" alt="image" src="https://user-images.githubusercontent.com/58853195/205618389-cecaaac9-4db2-4975-944d-8f53a40e0422.png">

> Do we really need a third sub navigation?

https://xd.adobe.com/view/55025386-7a36-4347-a725-4e138c0c6ea7-0051/screen/d1ca3264-1934-46b2-9384-4a55816b381f
I mean, this won't be easy to use afterwards it is like a dropdown in a dropdown.


And last feedback: How do you manage differencies between (internal) users and external users? Do external users see this navigation (mention of "All users" is done in the MIP)? Or would it be possible to let them see another navigation?

Thanks

**Comment by mkrout** [comment]
> * Where the portlet will be positonned ? dynamic container  ? in the top bar itself ? how it will be added in the portal ? can you describe for new customer ? for existing customer which migrate ?

The portlet should be positionned in MiddleToolBarTDContainer and added by configuration of org.exoplatform.commons.addons.AddOnService

**Comment by mkrout** [comment]
> données



> 



> 

@margondicco 
Nous avons besoin d'utliser un dynamic container pour ajouter la portlet, cependant l'affichage peux etre toujours gerer par des permissions et on peux aussi utiliser un feature flag pour afficher ou pas la portlet pour les clients

Pour la partie setting, on mettra en place le service pour les setting avec une conf par defaut, en attendant l'ajout de drawer de configuration pour une prochaine version

**Comment by margondicco** [comment]
> Nous avons besoin d'utliser un dynamic container pour ajouter la portlet, c

@mkrout @rdenarie : i really don't like the dynamic container and i don't like properties. My proposal for a MVP : we should add manually the portlet

**Comment by margondicco** [comment]
@Samuel-Renault-eXo thank you. We should work on the mobile design. We'll take your feedback into account

> And last feedback: How do you manage differencies between (internal) users and external users? Do external users see this navigation (mention of "All users" is done in the MIP)? Or would it be possible to let them see another navigation?

By defaut : Only for platform/users BUT the portlet displays only the nodes related to the user's permissions. So we could imagine to define some node dedicated for external users

> level 3 

i agree 3 levels aren't a best practice but .... So we should provide the better way to display the 3th level

**Comment by mkrout** [comment]
> > Nous avons besoin d'utliser un dynamic container pour ajouter la portlet, c
> 
> @mkrout @rdenarie : i really don't like the dynamic container and i don't like properties. My proposal for a MVP : we should add manually the portlet

The portlet should be added to the top bar, and it cannot be added manually since there is no way to edit this bar, the only way to do it is by configuration.

**Comment by rdenarie** [comment]
@margondicco I confirm that the portlet cannot be added manually. 

@mkrout can we imagine an initial state which display nothing until a user configure the portlet ? (choose the template, the root node, nevermind, but 'activate' the configuration ?) Before it is configured, it display nothing, as currently, after it is configured it is displayed ?
Or a configuration field "activated" ? so that, we can remove it without having to update the configuration ?

**Comment by mkrout** [comment]
> @margondicco I confirm that the portlet cannot be added manually.
> 
> @mkrout can we imagine an initial state which display nothing until a user configure the portlet ? (choose the template, the root node, nevermind, but 'activate' the configuration ?) Before it is configured, it display nothing, as currently, after it is configured it is displayed ? Or a configuration field "activated" ? so that, we can remove it without having to update the configuration ?

@rdenarie Maybe we can add an activated switch to the setting drawer, and by default it's set to false so nothing will be displayed, only the setting icon will be visible for an admin on mouseover. @margondicco WDYT?

**Comment by margondicco** [comment]
@mkrout @rdenarie : i suggest to add a switch button in the branding portlet "Activate top bar navigation"

cc @Samuel-Renault-eXo

**Comment by margondicco** [comment]
MIP updated after the product comitee

**Comment by boubaker** [comment]
> CMS - Navigation portlet

Is this the appropriate title for the MIP knowing that it's about reworking the navigation portlet ?

> Permissions : platform/users

Why not all authenticated users including external users ?

> Add a switch button : "Activate the top bar navigation"
> Add a feature exo.feature.navigationPortlet.enabled, default to false i.e. do not display the feature until it is possible to manage the node to appear in the portlet

Why adding a complexity in features and source code to maintain while it's an evolution of features that should be proposed to all end users without rollback to old navigation menu status.
In fact, a lot of Man-days will be used to maintain this flexibility. I suggest to keep it simple and just replace the current navigation bar by the new one.
I propose to use feature flags wisely and not for every new feature.

> NavigationMain.vue

No need to go into details for the technical specification, it's just to summarize modelization of complex business rules and software architecture

> this service should use the org.exoplatform.commons.api.settings.SettingService

ok you described the "How" but not the "Why" ? Why should we rely on "SettingService" while we should use NavigationService of MOP API ?

@rdenarie @margondicco @Samuel-Renault-eXo

**Comment by margondicco** [comment]
Hello @boubaker i'll try to explain : 


>Is this the appropriate title for the MIP knowing that it's about reworking the navigation portlet ?

in fact not : it's a new application not a reworking of an existing portlet. Perhaps the name of this portlet is wrong.

3 navigations portlet already exist : site navigation portlet, group navigation portlet, an old navigation portlet. We should fin a new great name !  my proposal : deleletion of the old navigation portlet and  creation of a new navigation portlet

> Why not all authenticated users including external users ?

It's a MVP : but a short term, the node displayed in this new portlet will take into account the permissions on the nodes (linked to pages or not) (another MIP)

>Add a feature exo.feature.navigationPortlet.enabled, default to false i.e. do not display the feature until it is possible to manage the node to appear in the portlet

The purpose of this flag as Meeds Lab will not need this new portlet immediately. 
The flag should make the parameter visible or not in the branding portlet. The default status of this parameters will be false


> other point

the technical part has not yet been reviewed by @mkrout 

Thank you

**Comment by mkrout** [comment]
> > CMS - Navigation portlet
> 
> Is this the appropriate title for the MIP knowing that it's about reworking the navigation portlet ?
> 
> > Permissions : platform/users
> 
> Why not all authenticated users including external users ?
IMO it shoud be changed, the portlet should be displayed for all authenticated users
> 
> > Add a switch button : "Activate the top bar navigation"
> > Add a feature exo.feature.navigationPortlet.enabled, default to false i.e. do not display the feature until it is possible to manage the node to appear in the portlet
> 
> Why adding a complexity in features and source code to maintain while it's an evolution of features that should be proposed to all end users without rollback to old navigation menu status. In fact, a lot of Man-days will be used to maintain this flexibility. I suggest to keep it simple and just replace the current navigation bar by the new one. I propose to use feature flags wisely and not for every new feature.
> 
> > NavigationMain.vue
> 
> No need to go into details for the technical specification, it's just to summarize modelization of complex business rules and software architecture
>
 Ok
> > this service should use the org.exoplatform.commons.api.settings.SettingService
> 
> ok you described the "How" but not the "Why" ? Why should we rely on "SettingService" while we should use NavigationService of MOP API ?

The Setting service (for this version of the portlet) will only store the value of the switch (added to the branding portlet)

> 
> @rdenarie @margondicco @Samuel-Renault-eXo

**Comment by rdenarie** [comment]
@mkrout can/should we use the FeatureService to set if the navigation portlet is available or not

**Comment by mkrout** [comment]
> @mkrout can/should we use the FeatureService to set if the navigation portlet is available or not
We used the feature service to activate the feature, no need to use the setting service anymore since we will not add the ability to the admin to activate/disable the portlet via UI

**Comment by boubaker** [comment]
> We used the feature service to activate the feature, no need to use the setting service anymore since we will not add the ability to the admin to activate/disable the portlet via UI

In fact, even if it's something that we want to enable/disable by UI, the FeatureService has a "persistent" state for its flags that can be changed via  dedicated REST Endpoint. I let you check on it here : 
https://github.com/Meeds-io/commons/blob/develop/commons-component-common/src/main/java/org/exoplatform/settings/impl/ExoFeatureServiceImpl.java#L45
and here
https://github.com/Meeds-io/commons/blob/develop/commons-component-common/src/main/java/org/exoplatform/settings/impl/ExoFeatureServiceImpl.java#L84-L95

**Comment by rdenarie** [comment]
Thank @mkrout 
@boubaker can you give a go tech if it is ok for you ?

**Comment by rdenarie** [comment]
To deliver the Mips on developer side : 
We need to remove feature flags tests when preparing PR on develop. 

PRs will be pushed on feature branch mips, in order to let Meeds Team test it. 
In parallel, Meeds Team will prepare meeds site configuration to add missing page/nodes in order to use correctly the feature

**Comment by boubaker** [comment]
PRs approved, you can proceed to deliver on develop, thanks.
