### ISSUE TITLE
Remove Juzu dependency

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/MIPs#82]
## Rationale

Juzu dependency has been deprecated and replaced by Vue & REST based Portlets. This dependency isn't maintained anymore.

### Upgradability

No Upgrades are needed to delete this dependency.
This dependency has to be removed from Dependency Tree of Meeds of all subsequent projects.

### Existing Features

No changes on existing Features

**Comment by boubaker** [comment]
@rdenarie ready for review

**Comment by rdenarie** [comment]
As I understand we need to rework the notification administration page in order to remove this dependency right ?

Perhaps, could you add a line about that in the description ?

In addition, we have a dependency on juzu for ChatServer. I need to check if we can remove it, or if we should keep temporaly the dependency at exo level.

Could you inform me when you put pr in feature/mips branches so that I can check ?
Thanks

**Comment by boubaker** [comment]
> As I understand we need to rework the notification administration page in order to remove this dependency right ?
> 
> Perhaps, could you add a line about that in the description ?

Not a line, but a whole MIP for this Upgrade indeed: https://github.com/Meeds-io/MIPs/issues/79

**Comment by boubaker** [comment]
> Could you inform me when you put pr in feature/mips branches so that I can check ?

Yep, of course, as usual; following the MIP process. In fact, I spited the functional need to rework the UI and the technical need to delete effectively Juzu from Meeds Bundle into two MIPs to allow you take the time to make the copy of Juzu Artifacts into eXo side if needed before merging into develop.

**Comment by boubaker** [comment]
@rdenarie PRs ready to review and Commits added to MIPs FB.

**Comment by rdenarie** [comment]
PR approved
